In [19]:
import numpy as np

#----------создание массивов различными способами--------------------------#
arr1 = np.array([1, 2, 3, 4, 5])
zeros = np.zeros((2, 3))      #матрица из нулей размером строки х столбцы
ones = np.ones((2, 4))        #матрица из единиц строки х столбцы
identity = np.eye(4)          #единичная матрица
range_arr = np.arange(0, 10, 2.2)  # [0, 2, 4, 6, 8] - создание массива с шагом от одного значения включительно до определенного значения невключительно

#--------------------------------использование атрибутов shape, dtype------#
print(arr1.shape) #размерность массива - количество элементов
print(arr1.dtype) #тип элементов
print(zeros.shape) #размерность матрицы - количество строк х столбцов
print(range_arr.dtype) #тип данных (элементов)
#--------------------------индексирование и срезы--------------------------#
element1 = arr1[0]; #элемент по индексу 0
print(element1)
element2 = identity[0, 0] #элемент в матрице по 1 столбцу 1 строке
print(element2) 
part_of_arr = arr1[:2]; #срез массива - данные от начала до 2 элемента включительно
print(part_of_arr) 
part_of_matrix = ones[:1,:3] #срез матрицы - 1 строка, 1-3 столбцы
print(part_of_matrix)
#--------------------------векторные операции и базовые статистики--------------------------#

a = np.array([1, -3, 3, 1, 5])
b = np.array([-5, 20, 30, 40, 50])

print(a + b)   # [-4 17 33 41 55] - сложение
print(a - b)   # [  6 -23 -27 -39 -45] - вычитание
print(a * b)   # [ -5 -60  90  40 250] - умножение
print(b / a)   # [-5.         -6.66666667 10.         40.         10.        ] - деление
print(a ** 2)  # [ 1  9  9  1 25] - возведение в степень

mean_value = np.mean(a) #вычисление среднего значения
print(f"Среднее значение: {mean_value}")


(5,)
int32
(2, 3)
float64
1
1.0
[1 2]
[[1. 1. 1.]]
[-4 17 33 41 55]
[  6 -23 -27 -39 -45]
[ -5 -60  90  40 250]
[-5.         -6.66666667 10.         40.         10.        ]
[ 1  9  9  1 25]
Среднее значение: 1.4
